name: 'Push and Publish'
description: 'Push code to repository and publish secrets to remote repository'
inputs:
  token: #organization and repository name
    description: 'The repository to push to'
    required: true
  gh_token:
    description: 'gh_token'
    required: true
runs:
  using: 'composite'
  steps:
    - run: npm install
      shell: bash
    - run: node index.js '${{inputs.token}}' '${{inputs.gh_token}}'
      shell: bash
      env:
        MY_SUPER_TOKEN: ${{inputs.token}}
