name: 'Push and Publish'
description: 'Push code to repository and publish secrets to remote repository'
inputs:
  token: #organization and repository name
    description: 'The repository to push to'
    required: true
runs:
  using: 'composite'
  steps:
    - run: node index.js '${{inputs.token}}'
      shell: bash
