name: 'NPM publisher'
description: 'Push code to repository and create new tag'
inputs:
  destinationRepository: #organization and repository name
    description: 'The repository to push to'
    required: false
    #default: ${{github.repository}}
  destinationPath: #path to folder
    description: 'The folder to push to'
    required: false
    default: '/'
runs:
  using: 'node12'
  main: 'index.js'
