name: 'NPM publisher'
description: 'Push code to repository and create new tag'
inputs:
  destinationRepository: #organization and repository name
    description: 'The repository to push to'
    required: false
    #default: ${{github.repository}}
  destinationPath: #path to folder
    description: 'The folder to push to'
    required: false
    default: '/'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        repository: VladimirZaets/postMessages
        path: myVladimirZaets/postMessages
    - run: node index.js
      shell: bash
    - run: cd javascript-client
      shell: bash
    - name: Tag
      id: autotagger
      uses: butlerlogic/action-autotag@stable
      with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - run: echo CREATED ${{steps.autotagger.outputs.tagcreated}}
      shell: bash
