name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: npm install
      - name: test
        id: test
        uses: ./

        #add install

