name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
            config-file: 'test_data/config.yml'
            openapi-url: 'https://raw.githubusercontent.com/openapi-generators/openapi-python-client/main/end_to_end_tests/openapi.json'
      - run: cd rust-client
      - name: test
        id: test
        uses: ./

        #add install

