name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: cd javascript-client
      - name: test
        id: test
        uses: ./
        with:
          token: 'hello world'


